# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Grunt + BrowserSync for livereload
    datasource:
#       driver-class-name: org.h2.jdbcx.JdbcDataSource
#       url: jdbc:h2:mem:spring_boot_sample;DB_CLOSE_DELAY=-1
        driverClassName: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/spring_boot_sample?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true
        name:
        username: root
        password:
    jpa:
#       database-platform: org.hibernate.dialect.H2Dialect
#       database: H2
        database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
        database: MYSQL
        show_sql: true
        hibernate:
            ddl-auto: update
#           ddl-auto: create-drop
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    mail:
        host: localhost
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false

server:
    port: 9090